### ISSUE TITLE
对比oraclize你们有什么优势？

### ISSUE THREAD

**Issue by huahuayu** [DOSNetwork/docs#1]

**Comment by dryruner** [comment]
Hi huahuayu,

Oraclize provides an easy-to-use and understandable interface to developers, so we adopt a similar interface. However, there’re a lot of intrinsic differences from Oraclize:

1. For uptime and decentralization - Oraclize is a centralized service, it’s prone to targeted attacks and it is a Single Point of Failure (SPOF) in the whole stack. During its downtime all the contracts/Dapps relying on Oraclize is non-usable. There are some of its downtime records, to give you some hints: https://twitter.com/oraclizeit/status/1022718553307398144; https://twitter.com/oraclizeit/status/989395126609956865; https://twitter.com/oraclizeit/status/966845312861077504; https://twitter.com/oraclizeit/status/964382990775103488. However, since DOS Network is a decentralized oracle network there’s no such concern about service downtime, there’re always node groups alive to be selected to serve the request.

2. For proofs and verification - Oraclize is using TLSNotary proof to prove its honesty. Ironically, here’s a dilemma that TLSNotary proofs themselves cannot be easily verified on-chain by the calling contract in real time - the proofs are mainly for auditing purposes afterwards. As a contrast, the proof in DOS Network is collectively generated in a cryptographic way by a randomly selected group. Also the proof is verified every time before handling the response back to the requester.

3. For payment & governance: Since Oraclize is operating as a for-profit company, it’s charging extra fees for each response. Per our analysis, requesters are paying roughly >200% of a response actually costs. Running as a DAO, we anticipate it to be more economic for requesters/developers to use DOS Network - DOS Network wouldn’t charge any premium besides service fees, and the service fees go to node runners. Requesters could also pay stablecoins (like DAI, USDC, TUSD, etc.) as service fees - this enables a more stable pricing model. Node runners could participate in the protocol governance to determine the fee structure and fee models. 

4. Running as a layer 2 network with the ability to support multiple blockchains, an application layer protocol could be built with DOS Network to enable cross-chain contract calls, a much more interesting topic yet to be discussed. 

Please stay tuned for more info from our whitepaper and beta releases in the near future.
